services:
  postgres:
    image: postgres:latest
    container_name: invoice-issuance-system-postgres
    environment:
      POSTGRES_DB:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
