spring.application.name=invoice-issuance-system

spring.datasource.url=${KEY_POSTGRES_URL}
spring.datasource.username=${KEY_POSTGRES_USER}
spring.datasource.password=${KEY_POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

security.config.prefix=${JWT_PREFIX}
security.config.key=${JWT_SECRET_KEY}
security.config.expiration=${JWT_EXPIRATION}
