spring.application.name=invoice-issuance-system

spring.datasource.url=jdbc:postgresql://localhost:5432/invoice_issuance_system_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
